
import { Service } from "./types";

export const MOCK_SERVICES: Service[] = [
  {
    id: "svc_01",
    name: "Trị liệu Thư giãn Toàn thân",
    description: "Liệu pháp massage chuyên sâu giúp giải tỏa căng thẳng, cải thiện tuần hoàn máu và mang lại giấc ngủ ngon.",
    durationMinutes: 60,
    price: 590000,
    category: "Massage",
    imageUrl: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=1000",
    isPopular: true,
  },
  {
    id: "svc_02",
    name: "Chăm sóc Da mặt Chuyên sâu",
    description: "Quy trình 12 bước với tinh chất collagen giúp tái tạo làn da, mờ nếp nhăn và sáng mịn tự nhiên.",
    durationMinutes: 90,
    price: 1200000,
    category: "Facial",
    imageUrl: "https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&q=80&w=1000",
    isPopular: true,
  },
  {
    id: "svc_03",
    name: "Gội đầu Dưỡng sinh Đông y",
    description: "Kết hợp massage cổ vai gáy và thảo dược thiên nhiên, giúp giảm đau đầu và thư giãn tuyệt đối.",
    durationMinutes: 45,
    price: 250000,
    category: "Hair Care",
    imageUrl: "https://images.unsplash.com/photo-1516975080664-ed2fc6a32937?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "svc_04",
    name: "Xông hơi Đá muối Himalaya",
    description: "Thanh lọc cơ thể, đào thải độc tố và tăng cường hệ miễn dịch với phòng xông đá muối nhập khẩu.",
    durationMinutes: 30,
    price: 150000,
    category: "Sauna",
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "svc_05",
    name: "Massage Chân Bấm huyệt",
    description: "Kích thích các huyệt đạo bàn chân giúp đả thông kinh mạch và cải thiện sức khỏe nội tạng.",
    durationMinutes: 45,
    price: 350000,
    category: "Massage",
    imageUrl: "https://images.unsplash.com/photo-1519823551278-64ac92734fb1?auto=format&fit=crop&q=80&w=1000",
  },
  {
    id: "svc_06",
    name: "Combo Thư giãn Thượng hạng",
    description: "Kết hợp Massage Body, Facial và Xông hơi. Trải nghiệm trọn vẹn sự thư thái đỉnh cao.",
    durationMinutes: 150,
    price: 2500000,
    category: "Package",
    imageUrl: "https://images.unsplash.com/photo-1600334089648-b0d9d3028eb2?auto=format&fit=crop&q=80&w=1000",
    isPopular: true,
  },
];
