import { Customer } from "./types";

export const MOCK_CUSTOMERS: Customer[] = [
  {
    id: "cust-1",
    full_name: "Phạm Thị Hoa",
    phone_number: "0912345678",
    email: "hoa.pham@example.com",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Hoa",
    is_active: true,
    gender: "FEMALE",
    date_of_birth: "1990-05-20",
    address: "123 Nguyễn Huệ, Q1, TP.HCM",
    allergies: "Dị ứng phấn hoa",
    medical_notes: "Da nhạy cảm, dễ kích ứng với mỹ phẩm chứa cồn",
    preferred_staff_id: null,
    created_at: "2024-01-15T08:00:00Z",
    updated_at: "2024-01-15T08:00:00Z",
  },
  {
    id: "cust-2",
    full_name: "Trần Minh Tuấn",
    phone_number: "0987654321",
    email: "tuan.tran@example.com",
    avatar_url: "https://api.dicebear.com/7.x/avataaars/svg?seed=Tuan",
    is_active: true,
    gender: "MALE",
    date_of_birth: "1985-12-15",
    address: "45 Lê Lợi, Q1, TP.HCM",
    allergies: null,
    medical_notes: "Thường xuyên đau mỏi vai gáy",
    preferred_staff_id: "staff-1",
    created_at: "2024-02-10T10:30:00Z",
    updated_at: "2024-02-10T10:30:00Z",
  },
  {
    id: "cust-3",
    full_name: "Lê Thu Thảo",
    phone_number: "0901234567",
    email: "thao.le@gmail.com",
    avatar_url: null,
    is_active: true,
    gender: "FEMALE",
    date_of_birth: "1995-08-08",
    address: "Biệt thự Lan Anh, Q2",
    allergies: "Hải sản",
    medical_notes: "Đang mang thai tuần thứ 12",
    preferred_staff_id: "staff-2",
    created_at: "2024-03-05T14:15:00Z",
    updated_at: "2024-03-05T14:15:00Z",
  },
  {
    id: "cust-4",
    full_name: "Chị Lan (Vãng lai)",
    phone_number: "0999888777",
    email: null,
    avatar_url: null,
    is_active: true,
    gender: "FEMALE",
    date_of_birth: null,
    address: null,
    allergies: null,
    medical_notes: "Khách gọi điện đặt lần đầu",
    preferred_staff_id: null,
    created_at: "2025-12-11T09:00:00Z",
    updated_at: "2025-12-11T09:00:00Z",
  },
];
