export const OPERATING_HOURS_UI = {
  COPY_TO_ALL: "Áp dụng tất cả",
  COPY_TOOLTIP: "Áp dụng cấu hình này cho tất cả các ngày",
  PASTE_SUCCESS_ALL: (day: string) => `Đã áp dụng cấu hình ${day} cho tất cả các ngày`,
  PASTE_SUCCESS_SINGLE: (src: string, dest: string) => `Đã dán cấu hình từ ${src} sang ${dest}`,
  COPY_INFO: (day: string) => `Đã chọn ${day}. Chọn ngày khác để dán hoặc áp dụng cho tất cả.`,
  CANCEL: "Hủy",
  SAVE_SUCCESS: "Lưu thay đổi thành công",
  SAVE_ERROR: "Đã có lỗi xảy ra khi lưu cấu hình",
  RESET: "Đã khôi phục cài đặt gốc",
  FROM_LABEL: "Từ:",
  STANDARD_TAB: "Tiêu chuẩn",
  EXCEPTIONS_TAB: "Ngoại lệ",
  DESCRIPTION_TITLE: "Thiết lập giờ mở cửa mặc định cho từng ngày trong tuần.",
  ADD_EXCEPTION_SUCCESS: (count: number) => `Đã thêm ${count} ngày ngoại lệ mới`,
  REMOVE_EXCEPTION_SUCCESS: (count: number) => count > 1 ? `Đã xóa ${count} mục` : "Đã xóa ngày ngoại lệ",
  SAVE_CHANGES: "Lưu thay đổi",
  CANCEL_CHANGES: "Hủy thay đổi",
} as const;
