"""change_services_timestamps_to_timestamptz

Revision ID: 1154b080905b
Revises: 9dacc5921c70
Create Date: 2025-11-30 16:39:51.166321

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '1154b080905b'
down_revision: Union[str, None] = '9dacc5921c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
