"""add_index_is_active

Revision ID: 5184042d30df
Revises: bf6b6793c292
Create Date: 2025-12-28 21:04:17.428216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5184042d30df'
down_revision: Union[str, None] = 'bf6b6793c292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_services_is_active'), 'services', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_is_active'), table_name='services')
    # ### end Alembic commands ###