"""add resource occupancy

Revision ID: 7e40273d288a
Revises: 1d1d0e43c8fc
Create Date: 2025-12-25 14:26:41.555016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e40273d288a'
down_revision: Union[str, None] = '1d1d0e43c8fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service_resource_requirements', sa.Column('start_delay', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('service_resource_requirements', sa.Column('usage_duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service_resource_requirements', 'usage_duration')
    op.drop_column('service_resource_requirements', 'start_delay')
    # ### end Alembic commands ###
