"""add_cascade_delete_to_service_skills

Revision ID: 9dacc5921c70
Revises: d3ab1cef886b
Create Date: 2025-11-30 12:07:40.936457

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '9dacc5921c70'
down_revision: Union[str, None] = 'd3ab1cef886b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('service_skills_skill_id_fkey', 'service_skills', type_='foreignkey')
    op.drop_constraint('service_skills_service_id_fkey', 'service_skills', type_='foreignkey')
    op.create_foreign_key(None, 'service_skills', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'service_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_skills', type_='foreignkey')
    op.drop_constraint(None, 'service_skills', type_='foreignkey')
    op.create_foreign_key('service_skills_service_id_fkey', 'service_skills', 'services', ['service_id'], ['id'])
    op.create_foreign_key('service_skills_skill_id_fkey', 'service_skills', 'skills', ['skill_id'], ['id'])
    # ### end Alembic commands ###
