"""add billing module tables

Revision ID: b9df64f282fd
Revises: f3ad2f608803
Create Date: 2025-12-19 20:48:42.922683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b9df64f282fd'
down_revision: Union[str, None] = 'f3ad2f608803'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('booking_id', sa.Uuid(), nullable=True),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('total_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'UNPAID', 'PARTIALLY_PAID', 'PAID', 'VOID', name='invoicestatus'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(scale=2), nullable=False),
    sa.Column('payment_method', sa.Enum('CASH', 'BANK_TRANSFER', 'CREDIT_CARD', 'E_WALLET', name='paymentmethod'), nullable=False),
    sa.Column('transaction_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('invoices')
    # ### end Alembic commands ###
