"""add customers table

Revision ID: bb752c48cecd
Revises: ea1fb0d267ca
Create Date: 2025-12-19 18:44:32.603850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb752c48cecd'
down_revision: Union[str, None] = 'ea1fb0d267ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('membership_tier', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allergies', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medical_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_staff_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['preferred_staff_id'], ['staff.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_customers_phone_number'), 'customers', ['phone_number'], unique=True)
    op.alter_column('booking_items', 'staff_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK tới staff - KTV thực hiện (có thể assign sau)',
               existing_nullable=True)
    op.alter_column('booking_items', 'resource_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK tới resources - Phòng/Máy sử dụng (có thể assign sau)',
               existing_nullable=True)
    op.alter_column('booking_items', 'service_name_snapshot',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Snapshot tên dịch vụ tại thời điểm đặt',
               existing_nullable=True)
    op.alter_column('booking_items', 'original_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment=None,
               existing_comment='Giá gốc tại thời điểm đặt (không thay đổi khi service thay giá)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('booking_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_booking_items_booking_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_resource_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_staff_id'), table_name='booking_items')
    op.drop_index(op.f('ix_booking_items_time_range'), table_name='booking_items')
    op.drop_table_comment(
        'booking_items',
        existing_comment='Chi tiết từng dịch vụ trong lịch hẹn - Activity trong mô hình RCPSP',
        schema=None
    )
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK tới users - Khách hàng đặt lịch',
               existing_nullable=True)
    op.alter_column('bookings', 'created_by',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK tới users - Lễ tân/Admin tạo booking',
               existing_nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='booking_status'),
               comment=None,
               existing_comment='Trạng thái: PENDING → CONFIRMED → IN_PROGRESS → COMPLETED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::booking_status"))
    op.alter_column('bookings', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('bookings', 'cancel_reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('bookings', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Thời điểm khách check-in',
               existing_nullable=True)
    op.alter_column('bookings', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               comment=None,
               existing_comment='Tổng giá dịch vụ (tự động tính từ items)',
               existing_server_default=sa.text('0'))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_bookings_customer_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_start_time'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_table_comment(
        'bookings',
        existing_comment='Lịch hẹn của khách hàng',
        schema=None
    )
    op.alter_column('resource_groups', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('resource_groups', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('resource_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_resource_groups_type'), table_name='resource_groups')
    op.drop_table_comment(
        'resource_groups',
        existing_comment='Nhóm tài nguyên logic (VD: Phòng đơn, Phòng VIP, Máy Laser...)',
        schema=None
    )
    op.alter_column('resources', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Sức chứa (số khách tối đa cùng lúc)',
               existing_server_default=sa.text('1'))
    op.alter_column('resources', 'setup_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Thời gian chuẩn bị/dọn dẹp giữa các ca',
               existing_server_default=sa.text('0'))
    op.alter_column('resources', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('resources', 'image_url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('resources', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_resources_group_id'), table_name='resources')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_table_comment(
        'resources',
        existing_comment='Tài nguyên vật lý cụ thể (VD: Phòng VIP 1, Máy Laser 01...)',
        schema=None
    )
    op.alter_column('service_categories', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('service_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Thứ tự hiển thị trên giao diện',
               existing_server_default=sa.text('0'))
    op.alter_column('service_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'service_categories',
        existing_comment='Danh mục phân loại dịch vụ Spa (VD: Massage, Skincare, Tẩy da chết...)',
        schema=None
    )
    op.alter_column('service_resource_requirements', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Số lượng tài nguyên cần (VD: 1 Phòng đơn)',
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_service_resource_requirements_service_id'), table_name='service_resource_requirements')
    op.drop_table_comment(
        'service_resource_requirements',
        existing_comment='Định nghĩa dịch vụ cần bao nhiêu tài nguyên thuộc nhóm nào',
        schema=None
    )
    op.drop_column('service_skills', 'min_proficiency_level')
    op.alter_column('services', 'category_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK tới danh mục dịch vụ',
               existing_nullable=True)
    op.alter_column('services', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('services', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               comment=None,
               existing_comment='Thời điểm xóa mềm (Soft Delete)',
               existing_nullable=True)
    op.drop_index(op.f('ix_services_category_id'), table_name='services')
    op.alter_column('shifts', 'start_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Giờ bắt đầu ca (VD: 08:00)',
               existing_nullable=False)
    op.alter_column('shifts', 'end_time',
               existing_type=postgresql.TIME(),
               comment=None,
               existing_comment='Giờ kết thúc ca (VD: 12:00)',
               existing_nullable=False)
    op.alter_column('shifts', 'color_code',
               existing_type=sa.VARCHAR(length=7),
               comment=None,
               existing_comment='Mã màu hiển thị trên calendar (#RRGGBB)',
               existing_nullable=True)
    op.alter_column('shifts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_shifts_name'), table_name='shifts')
    op.drop_table_comment(
        'shifts',
        existing_comment='Định nghĩa các ca làm việc cố định (Ca sáng, Ca chiều, Ca tối...)',
        schema=None
    )
    op.alter_column('staff_schedules', 'staff_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK tới staff.user_id - Nhân viên được phân công',
               existing_nullable=False)
    op.alter_column('staff_schedules', 'shift_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='FK tới shifts.id - Ca làm việc',
               existing_nullable=False)
    op.alter_column('staff_schedules', 'work_date',
               existing_type=sa.DATE(),
               comment=None,
               existing_comment='Ngày làm việc cụ thể',
               existing_nullable=False)
    op.alter_column('staff_schedules', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', name='schedule_status'),
               comment=None,
               existing_comment='Trạng thái: DRAFT (nháp) hoặc PUBLISHED (công bố)',
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::schedule_status"))
    op.alter_column('staff_schedules', 'notes',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               comment=None,
               existing_comment='Ghi chú (VD: Làm thêm, Thay thế...)',
               existing_nullable=True)
    op.alter_column('staff_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_staff_schedules_date'), table_name='staff_schedules')
    op.drop_index(op.f('ix_staff_schedules_staff_date'), table_name='staff_schedules')
    op.drop_index(op.f('ix_staff_schedules_status'), table_name='staff_schedules')
    op.drop_constraint(op.f('staff_schedules_unique'), 'staff_schedules', type_='unique')
    op.drop_table_comment(
        'staff_schedules',
        existing_comment='Phân công lịch làm việc cho nhân viên theo ngày và ca',
        schema=None
    )
    op.drop_column('staff_skills', 'proficiency_level')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('staff_skills', sa.Column('proficiency_level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='Mức thành thạo (1=Cơ bản, 2=Thành thạo, 3=Chuyên gia)'))
    op.create_table_comment(
        'staff_schedules',
        'Phân công lịch làm việc cho nhân viên theo ngày và ca',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(op.f('staff_schedules_unique'), 'staff_schedules', ['staff_id', 'work_date', 'shift_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_staff_schedules_status'), 'staff_schedules', ['status'], unique=False)
    op.create_index(op.f('ix_staff_schedules_staff_date'), 'staff_schedules', ['staff_id', 'work_date'], unique=False)
    op.create_index(op.f('ix_staff_schedules_date'), 'staff_schedules', ['work_date'], unique=False)
    op.alter_column('staff_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('staff_schedules', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               comment='Ghi chú (VD: Làm thêm, Thay thế...)',
               existing_nullable=True)
    op.alter_column('staff_schedules', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PUBLISHED', name='schedule_status'),
               comment='Trạng thái: DRAFT (nháp) hoặc PUBLISHED (công bố)',
               existing_nullable=False,
               existing_server_default=sa.text("'DRAFT'::schedule_status"))
    op.alter_column('staff_schedules', 'work_date',
               existing_type=sa.DATE(),
               comment='Ngày làm việc cụ thể',
               existing_nullable=False)
    op.alter_column('staff_schedules', 'shift_id',
               existing_type=sa.UUID(),
               comment='FK tới shifts.id - Ca làm việc',
               existing_nullable=False)
    op.alter_column('staff_schedules', 'staff_id',
               existing_type=sa.UUID(),
               comment='FK tới staff.user_id - Nhân viên được phân công',
               existing_nullable=False)
    op.create_table_comment(
        'shifts',
        'Định nghĩa các ca làm việc cố định (Ca sáng, Ca chiều, Ca tối...)',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_shifts_name'), 'shifts', ['name'], unique=False)
    op.alter_column('shifts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('shifts', 'color_code',
               existing_type=sa.VARCHAR(length=7),
               comment='Mã màu hiển thị trên calendar (#RRGGBB)',
               existing_nullable=True)
    op.alter_column('shifts', 'end_time',
               existing_type=postgresql.TIME(),
               comment='Giờ kết thúc ca (VD: 12:00)',
               existing_nullable=False)
    op.alter_column('shifts', 'start_time',
               existing_type=postgresql.TIME(),
               comment='Giờ bắt đầu ca (VD: 08:00)',
               existing_nullable=False)
    op.create_index(op.f('ix_services_category_id'), 'services', ['category_id'], unique=False)
    op.alter_column('services', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               comment='Thời điểm xóa mềm (Soft Delete)',
               existing_nullable=True)
    op.alter_column('services', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('services', 'category_id',
               existing_type=sa.UUID(),
               comment='FK tới danh mục dịch vụ',
               existing_nullable=True)
    op.add_column('service_skills', sa.Column('min_proficiency_level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True, comment='Mức tối thiểu yêu cầu để thực hiện dịch vụ'))
    op.create_table_comment(
        'service_resource_requirements',
        'Định nghĩa dịch vụ cần bao nhiêu tài nguyên thuộc nhóm nào',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_service_resource_requirements_service_id'), 'service_resource_requirements', ['service_id'], unique=False)
    op.alter_column('service_resource_requirements', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Số lượng tài nguyên cần (VD: 1 Phòng đơn)',
               existing_server_default=sa.text('1'))
    op.create_table_comment(
        'service_categories',
        'Danh mục phân loại dịch vụ Spa (VD: Massage, Skincare, Tẩy da chết...)',
        existing_comment=None,
        schema=None
    )
    op.alter_column('service_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('service_categories', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Thứ tự hiển thị trên giao diện',
               existing_server_default=sa.text('0'))
    op.alter_column('service_categories', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table_comment(
        'resources',
        'Tài nguyên vật lý cụ thể (VD: Phòng VIP 1, Máy Laser 01...)',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_index(op.f('ix_resources_group_id'), 'resources', ['group_id'], unique=False)
    op.alter_column('resources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resources', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('resources', 'image_url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('resources', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('resources', 'setup_time_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Thời gian chuẩn bị/dọn dẹp giữa các ca',
               existing_server_default=sa.text('0'))
    op.alter_column('resources', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Sức chứa (số khách tối đa cùng lúc)',
               existing_server_default=sa.text('1'))
    op.create_table_comment(
        'resource_groups',
        'Nhóm tài nguyên logic (VD: Phòng đơn, Phòng VIP, Máy Laser...)',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_resource_groups_type'), 'resource_groups', ['type'], unique=False)
    op.alter_column('resource_groups', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('resource_groups', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('resource_groups', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table_comment(
        'bookings',
        'Lịch hẹn của khách hàng',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_start_time'), 'bookings', ['start_time'], unique=False)
    op.create_index(op.f('ix_bookings_customer_id'), 'bookings', ['customer_id'], unique=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bookings', 'total_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               comment='Tổng giá dịch vụ (tự động tính từ items)',
               existing_server_default=sa.text('0'))
    op.alter_column('bookings', 'check_in_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Thời điểm khách check-in',
               existing_nullable=True)
    op.alter_column('bookings', 'cancel_reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bookings', 'notes',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('bookings', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='booking_status'),
               comment='Trạng thái: PENDING → CONFIRMED → IN_PROGRESS → COMPLETED',
               existing_nullable=False,
               existing_server_default=sa.text("'PENDING'::booking_status"))
    op.alter_column('bookings', 'created_by',
               existing_type=sa.UUID(),
               comment='FK tới users - Lễ tân/Admin tạo booking',
               existing_nullable=True)
    op.alter_column('bookings', 'customer_id',
               existing_type=sa.UUID(),
               comment='FK tới users - Khách hàng đặt lịch',
               existing_nullable=True)
    op.create_table_comment(
        'booking_items',
        'Chi tiết từng dịch vụ trong lịch hẹn - Activity trong mô hình RCPSP',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('ix_booking_items_time_range'), 'booking_items', ['start_time', 'end_time'], unique=False)
    op.create_index(op.f('ix_booking_items_staff_id'), 'booking_items', ['staff_id'], unique=False)
    op.create_index(op.f('ix_booking_items_resource_id'), 'booking_items', ['resource_id'], unique=False)
    op.create_index(op.f('ix_booking_items_booking_id'), 'booking_items', ['booking_id'], unique=False)
    op.alter_column('booking_items', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('booking_items', 'original_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               comment='Giá gốc tại thời điểm đặt (không thay đổi khi service thay giá)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('booking_items', 'service_name_snapshot',
               existing_type=sa.VARCHAR(length=255),
               comment='Snapshot tên dịch vụ tại thời điểm đặt',
               existing_nullable=True)
    op.alter_column('booking_items', 'resource_id',
               existing_type=sa.UUID(),
               comment='FK tới resources - Phòng/Máy sử dụng (có thể assign sau)',
               existing_nullable=True)
    op.alter_column('booking_items', 'staff_id',
               existing_type=sa.UUID(),
               comment='FK tới staff - KTV thực hiện (có thể assign sau)',
               existing_nullable=True)
    op.drop_index(op.f('ix_customers_phone_number'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
