"""add_staff_tables

Revision ID: ea1fb0d267ca
Revises: 77c11fbbf9a0
Create Date: 2025-12-03 09:34:27.375074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea1fb0d267ca'
down_revision: Union[str, None] = '77c11fbbf9a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('hired_at', sa.Date(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('color_code', sa.String(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('staff_skills',
    sa.Column('staff_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('staff_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff_skills')
    op.drop_table('staff')
    # ### end Alembic commands ###
