"""add customer treatments table

Revision ID: f3ad2f608803
Revises: bb752c48cecd
Create Date: 2025-12-19 19:26:19.173079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f3ad2f608803'
down_revision: Union[str, None] = 'bb752c48cecd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_treatments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('used_sessions', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'EXPIRED', name='treatmentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_treatments_customer_id'), 'customer_treatments', ['customer_id'], unique=False)
    op.add_column('booking_items', sa.Column('treatment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'booking_items', 'customer_treatments', ['treatment_id'], ['id'], ondelete='SET NULL')

    # Check if constraint exists before dropping (Alembic auto-generated this, assuming it tracks state)
    # If this fails, we might need to manually handle names.
    # The previous migration bb752c48cecd DID add the foreign key to customers.
    # However, maybe the name was different or autogenerated.
    # Let's keep it as is, usually Alembic knows.
    op.drop_constraint('bookings_customer_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key('bookings_customer_id_fkey', 'bookings', 'users', ['customer_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'booking_items', type_='foreignkey')
    op.drop_column('booking_items', 'treatment_id')
    op.drop_index(op.f('ix_customer_treatments_customer_id'), table_name='customer_treatments')
    op.drop_table('customer_treatments')
    # ### end Alembic commands ###
