import { MOCK_SKILLS } from "@/features/services/model/mocks";
import { Staff } from "./types";

export const MOCK_STAFF: Staff[] = [
  {
    user_id: "1",
    hired_at: "2023-01-01T00:00:00Z",
    created_at: "2023-01-01T00:00:00Z",
    bio: "Quản lý có nhiều năm kinh nghiệm trong ngành spa.",
    title: "Quản lý",
    color_code: "#EF4444",
    commission_rate: 0,
    user: {
      id: "1",
      email: "admin@synapse.com",
      full_name: "Nguyễn Văn Quản Lý",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=admin",
      phone_number: "0901234567",
      role: "manager",
      is_active: true,
    },
    skills: [],
  },
  {
    user_id: "2",
    hired_at: "2023-02-01T00:00:00Z",
    created_at: "2023-02-01T00:00:00Z",
    bio: "Lễ tân nhiệt tình, chu đáo.",
    title: "Lễ tân",
    color_code: "#F97316",
    commission_rate: 0,
    user: {
      id: "2",
      email: "letan1@synapse.com",
      full_name: "Trần Thị Lễ Tân 1",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=letan1",
      phone_number: "0901234568",
      role: "receptionist",
      is_active: true,
    },
    skills: [],
  },
  {
    user_id: "3",
    hired_at: "2023-03-01T00:00:00Z",
    created_at: "2023-03-01T00:00:00Z",
    bio: "Lễ tân vui vẻ, hòa đồng.",
    title: "Lễ tân",
    color_code: "#F59E0B",
    commission_rate: 0,
    user: {
      id: "3",
      email: "letan2@synapse.com",
      full_name: "Lê Thị Lễ Tân 2",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=letan2",
      phone_number: "0901234569",
      role: "receptionist",
      is_active: true,
    },
    skills: [],
  },
  {
    user_id: "4",
    hired_at: "2023-04-01T00:00:00Z",
    created_at: "2023-04-01T00:00:00Z",
    bio: "Kỹ thuật viên tay nghề cao.",
    title: "Kỹ thuật viên",
    color_code: "#10B981",
    commission_rate: 10,
    user: {
      id: "4",
      email: "ktv1@synapse.com",
      full_name: "Phạm Văn Kỹ Thuật 1",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv1",
      phone_number: "0901234570",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[0], MOCK_SKILLS[1], MOCK_SKILLS[2]],
  },
  {
    user_id: "5",
    hired_at: "2023-05-01T00:00:00Z",
    created_at: "2023-05-01T00:00:00Z",
    bio: "Chuyên gội đầu dưỡng sinh.",
    title: "Kỹ thuật viên",
    color_code: "#14B8A6",
    commission_rate: 10,
    user: {
      id: "5",
      email: "ktv2@synapse.com",
      full_name: "Hoàng Thị Kỹ Thuật 2",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv2",
      phone_number: "0901234571",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[3], MOCK_SKILLS[4]],
  },
  {
    user_id: "6",
    hired_at: "2023-06-01T00:00:00Z",
    created_at: "2023-06-01T00:00:00Z",
    bio: "Chuyên gia về da liễu.",
    title: "Kỹ thuật viên",
    color_code: "#06B6D4",
    commission_rate: 15,
    user: {
      id: "6",
      email: "ktv3@synapse.com",
      full_name: "Vũ Văn Kỹ Thuật 3",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv3",
      phone_number: "0901234572",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[0], MOCK_SKILLS[5]],
  },
  {
    user_id: "7",
    hired_at: "2023-07-01T00:00:00Z",
    created_at: "2023-07-01T00:00:00Z",
    bio: "Kỹ thuật viên massage.",
    title: "Kỹ thuật viên",
    color_code: "#0EA5E9",
    commission_rate: 10,
    user: {
      id: "7",
      email: "ktv4@synapse.com",
      full_name: "Đặng Thị Kỹ Thuật 4",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv4",
      phone_number: "0901234573",
      role: "technician",
      is_active: false,
    },
    skills: [MOCK_SKILLS[1], MOCK_SKILLS[6]],
  },
  {
    user_id: "8",
    hired_at: "2023-08-01T00:00:00Z",
    created_at: "2023-08-01T00:00:00Z",
    bio: "Kỹ thuật viên chăm sóc da.",
    title: "Kỹ thuật viên",
    color_code: "#3B82F6",
    commission_rate: 10,
    user: {
      id: "8",
      email: "ktv5@synapse.com",
      full_name: "Bùi Văn Kỹ Thuật 5",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv5",
      phone_number: "0901234574",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[2], MOCK_SKILLS[7]],
  },
  {
    user_id: "9",
    hired_at: "2023-09-01T00:00:00Z",
    created_at: "2023-09-01T00:00:00Z",
    bio: "Kỹ thuật viên triệt lông.",
    title: "Kỹ thuật viên",
    color_code: "#6366F1",
    commission_rate: 10,
    user: {
      id: "9",
      email: "ktv6@synapse.com",
      full_name: "Ngô Thị Kỹ Thuật 6",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv6",
      phone_number: "0901234575",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[8], MOCK_SKILLS[0]],
  },
  {
    user_id: "10",
    hired_at: "2023-10-01T00:00:00Z",
    created_at: "2023-10-01T00:00:00Z",
    bio: "Kỹ thuật viên đa năng.",
    title: "Kỹ thuật viên",
    color_code: "#8B5CF6",
    commission_rate: 12,
    user: {
      id: "10",
      email: "ktv7@synapse.com",
      full_name: "Đỗ Văn Kỹ Thuật 7",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv7",
      phone_number: "0901234576",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[1], MOCK_SKILLS[4], MOCK_SKILLS[3]],
  },
  {
    user_id: "11",
    hired_at: "2023-11-01T00:00:00Z",
    created_at: "2023-11-01T00:00:00Z",
    bio: "Kỹ thuật viên chăm sóc da.",
    title: "Kỹ thuật viên",
    color_code: "#A855F7",
    commission_rate: 10,
    user: {
      id: "11",
      email: "ktv8@synapse.com",
      full_name: "Lý Thị Kỹ Thuật 8",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv8",
      phone_number: "0901234577",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[0], MOCK_SKILLS[2]],
  },
  {
    user_id: "12",
    hired_at: "2023-12-01T00:00:00Z",
    created_at: "2023-12-01T00:00:00Z",
    bio: "Kỹ thuật viên laser.",
    title: "Kỹ thuật viên",
    color_code: "#D946EF",
    commission_rate: 15,
    user: {
      id: "12",
      email: "ktv9@synapse.com",
      full_name: "Hồ Văn Kỹ Thuật 9",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv9",
      phone_number: "0901234578",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[1], MOCK_SKILLS[5]],
  },
  {
    user_id: "13",
    hired_at: "2024-01-01T00:00:00Z",
    created_at: "2024-01-01T00:00:00Z",
    bio: "Kỹ thuật viên gội đầu.",
    title: "Kỹ thuật viên",
    color_code: "#EC4899",
    commission_rate: 10,
    user: {
      id: "13",
      email: "ktv10@synapse.com",
      full_name: "Dương Thị Kỹ Thuật 10",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv10",
      phone_number: "0901234579",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[3], MOCK_SKILLS[8]],
  },
  {
    user_id: "14",
    hired_at: "2024-02-01T00:00:00Z",
    created_at: "2024-02-01T00:00:00Z",
    bio: "Kỹ thuật viên massage.",
    title: "Kỹ thuật viên",
    color_code: "#F43F5E",
    commission_rate: 10,
    user: {
      id: "14",
      email: "ktv11@synapse.com",
      full_name: "Mai Văn Kỹ Thuật 11",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv11",
      phone_number: "0901234580",
      role: "technician",
      is_active: false,
    },
    skills: [MOCK_SKILLS[4], MOCK_SKILLS[6]],
  },
  {
    user_id: "15",
    hired_at: "2024-03-01T00:00:00Z",
    created_at: "2024-03-01T00:00:00Z",
    bio: "Kỹ thuật viên peel da.",
    title: "Kỹ thuật viên",
    color_code: "#E11D48",
    commission_rate: 10,
    user: {
      id: "15",
      email: "ktv12@synapse.com",
      full_name: "Trương Thị Kỹ Thuật 12",
      avatar_url: "https://api.dicebear.com/9.x/avataaars/svg?seed=ktv12",
      phone_number: "0901234581",
      role: "technician",
      is_active: true,
    },
    skills: [MOCK_SKILLS[7], MOCK_SKILLS[0]],
  },
];
