import { addDays, subDays, subHours } from "date-fns";
import { Invoice } from "./types";

export const MOCK_INVOICES: Invoice[] = [
  {
    id: "INV-001",
    bookingId: "BK-001",
    customerId: "CUST-001",
    customerName: "Nguyễn Văn A",
    customerPhone: "0901234567",
    amount: 500000,
    paidAmount: 500000,
    status: "PAID",
    issuedAt: subDays(new Date(), 2),
    finalAmount: 500000,
    items: [
      {
        id: "ITEM-001",
        invoiceId: "INV-001",
        serviceId: "SERV-001",
        serviceName: "Cắt tóc nam",
        quantity: 1,
        unitPrice: 200000,
        totalPrice: 200000,
        type: "SERVICE",
      },
      {
        id: "ITEM-002",
        invoiceId: "INV-001",
        serviceId: "SERV-002",
        serviceName: "Gội đầu",
        quantity: 1,
        unitPrice: 150000,
        totalPrice: 150000,
        type: "SERVICE",
      },
      {
        id: "ITEM-003",
        invoiceId: "INV-001",
        productId: "PROD-001",
        productName: "Sáp vuốt tóc",
        quantity: 1,
        unitPrice: 150000,
        totalPrice: 150000,
        type: "PRODUCT",
      },
    ],
    payments: [
      {
        id: "PAY-001",
        invoiceId: "INV-001",
        amount: 500000,
        method: "CASH",
        transactionTime: subDays(new Date(), 2),
        createdBy: "staff-1",
      },
    ],
  },
  {
    id: "INV-002",
    bookingId: "BK-002",
    customerId: "CUST-002",
    customerName: "Trần Thị B",
    customerPhone: "0909876543",
    amount: 1200000,
    paidAmount: 500000,
    status: "UNPAID",
    issuedAt: subHours(new Date(), 4),
    finalAmount: 1200000,
    items: [
      {
        id: "ITEM-004",
        invoiceId: "INV-002",
        serviceId: "SERV-003",
        serviceName: "Massage toàn thân",
        quantity: 1,
        unitPrice: 1200000,
        totalPrice: 1200000,
        type: "SERVICE",
      },
    ],
    payments: [
      {
        id: "PAY-002",
        invoiceId: "INV-002",
        amount: 500000,
        method: "TRANSFER",
        transactionRef: "TXN123456",
        transactionTime: subHours(new Date(), 4),
        createdBy: "staff-1",
        note: "Đặt cọc",
      },
    ],
  },
  {
    id: "INV-003",
    bookingId: "BK-003",
    customerId: "CUST-003",
    customerName: "Lê Văn C",
    customerPhone: "0912345678",
    amount: 300000,
    paidAmount: 0,
    status: "UNPAID",
    issuedAt: new Date(),
    finalAmount: 300000,
    items: [
      {
        id: "ITEM-005",
        invoiceId: "INV-003",
        serviceId: "SERV-001",
        serviceName: "Cắt tóc nam",
        quantity: 1,
        unitPrice: 200000,
        totalPrice: 200000,
        type: "SERVICE",
      },
       {
        id: "ITEM-006",
        invoiceId: "INV-003",
        serviceId: "SERV-004",
        serviceName: "Cạo mặt",
        quantity: 1,
        unitPrice: 100000,
        totalPrice: 100000,
        type: "SERVICE",
      },
    ],
    payments: [],
  },
];
